[package]
name = "invalid-check"
version = "0.1.0"
authors = ["lucas7788 <sishsh@163.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "check"
path ="src/main.rs"

[dependencies]
parity-wasm = "0.35"
clap = "2.26.0"
